services:

  web:
    container_name: katsuyou-web-compose
    image: bluskyyy/katsuyou-web
    ports:
      - "81:81"
    depends_on:
      - api
    networks:
      - backend

  api:
    container_name: katsuyou-api-compose
    image: bluskyyy/api-test
    restart: always
    networks:
      - backend
    depends_on:
      - db

  db:
    container_name: katsuyou-db1-compose
    image: bluskyyy/db-test
    restart: always
    networks:
      - backend
    volumes:
      - JMDICT_DATA:/var/lib/mysql

volumes:
  JMDICT_DATA:

networks:
  backend:
    driver: bridge