spring.application.name=Katsuyou

## Connect to DB
spring.datasource.url=jdbc:mysql://db:3306/JMDict

spring.datasource.username=root
spring.datasource.password=uNLNpNTwmHvDT6kXySMR
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## JPA config
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl.auto=update