CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'uNLNpNTwmHvDT6kXySMR';
CREATE USER IF NOT EXISTS 'mysql'@'%' IDENTIFIED BY '9L8SfsbXjWwfkcH7ub6P';

GRANT ALL PRIVILEGES ON JMDict.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON JMDict.* TO 'mysql'@'%';

FLUSH PRIVILEGES;