CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'test';
CREATE USER IF NOT EXISTS 'mysql'@'%' IDENTIFIED BY 'test';

GRANT ALL PRIVILEGES ON JMDict.* TO 'root'@'%';
GRANT ALL PRIVILEGES ON JMDict.* TO 'mysql'@'%';

FLUSH PRIVILEGES;